name: Coverage

on: [ push ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Test
        run: yarn test

      - uses: codecov/codecov-action@v3
